### ISSUE TITLE
Update Google MDI icons

### ISSUE THREAD

**Issue by hanakin** [iconify-design/collections-json#3]
recently Google MDI released version 2.0 of there icons which now includes 5 themes of all their icons

baseline, outline, round, sharp, twotown

so

baseline-assessment
outline-assessment
round-assessment
twotone-assessment
sharp-assessment

they have not updated their github repo yet https://github.com/google/material-design-icons/issues/811 so the manual download is the only option at the moment https://material.io/tools/icons/?search=ass&icon=assignment&style=outline

**Comment by cyberalien** [comment]
Its more complex than that. If you look at https://material.io/tools/icons/?style=baseline you'll see there are variations of many icons. They are not in repository.

I suspect they are redesigning whole thing, but its work in progress they don't want to publish.

**Comment by hanakin** [comment]
its worse the problem is the organization of the repo is in no way automated. you could easily build all the png files from the svgs in a build step rather than including them. not to mention they like making size variations for some reason other than ios it makes no sense

**Comment by cyberalien** [comment]
That repository does seem to be almost completely abandoned. Possibly because Android now uses Vector Drawable format, so PNG icons are useless. Then different variations of icon is not easy to implement in font, so font is useless.

Latest icons set is not hard to get from their website, which is way superior to what's in their repository, so it might be something worth doing.

**Comment by cyberalien** [comment]
Created repository with updated icons: https://github.com/cyberalien/google-material-design-icons-updated

Its full set from https://material.io/tools/icons/

I'll add them to Iconify later today. First need to do some testing to make sure new version and old version are compatible, so there are no missing icons in new version.

**Comment by cyberalien** [comment]
Cleaned up, fixed broken icons and added to Iconify. Old icon names are working too for backwards compatibility.

Now search is a bit weird because themes and categories are mixed. Will need to update search to display it in a more friendly way.
