### ISSUE TITLE
add MB Class icons

### ISSUE THREAD

**Issue by maximmbc** [iconify-design/collections-json#4]
please add Mercedes-Benz Class free icons https://github.com/maximmbc/mbclass

**Comment by cyberalien** [comment]
Sorry, no. There are several reasons for it:

1. That set is very niche. How many websites would need different letters for MB brand?
2. Icons have very specific design. It uses fixed palette with gradients.
3. Icons set is very small.

This collection is meant for icons that are useful to many websites, not 1-2 websites.

If you want to use that icons set with Iconify, there are several other options:

1. You can host your own copy of API with those icons. See https://iconify.design/docs/api-hosting/

2. You can create custom bundle with those icons. See https://iconify.design/docs/icon-bundles/
I'm using this method on Iconify website to add custom icons such as logo and few other icons that are specific to my website.

3. Later I'll be adding possibly to upload custom icons that are not public, so they could be used with Iconify, which is I guess what you are looking for. However such functionality will not be available any time soon. It will take long time to develop. So for now I suggest using one of previous options.
